# netlify.toml — publish site/ only; robust ignore for README.md/push.sh-only commits
[build]
  publish = "site"
  ignore = '''
if [ -z "$CACHED_COMMIT_REF" ]; then
  # First build or no cache — proceed with build
  exit 1
fi

CHANGED=$(git diff --name-only "$CACHED_COMMIT_REF" "$COMMIT_REF")
# Build when any file other than README.md / push.sh changed
if echo "$CHANGED" | grep -vE '^(README\.md|push\.sh)$' | grep -q .; then
  exit 1
else
  echo "Skipping build: only README.md/push.sh changed"
  exit 0
fi
'''